use azalea_registry::builtin::ItemKind;

use crate::mwms::category::{ItemCategory, ItemCategoryProfile};

pub struct DefaultItemCategoryProfile;

impl ItemCategoryProfile for DefaultItemCategoryProfile {
    fn map_item_kind(&self, kind: &ItemKind) -> ItemCategory {
        match kind {
            ItemKind::Stone
            | ItemKind::Granite
            | ItemKind::PolishedGranite
            | ItemKind::Diorite
            | ItemKind::PolishedDiorite
            | ItemKind::Andesite
            | ItemKind::PolishedAndesite
            | ItemKind::Deepslate
            | ItemKind::CobbledDeepslate
            | ItemKind::PolishedDeepslate
            | ItemKind::Calcite
            | ItemKind::Tuff
            | ItemKind::TuffSlab
            | ItemKind::TuffStairs
            | ItemKind::TuffWall
            | ItemKind::ChiseledTuff
            | ItemKind::PolishedTuff
            | ItemKind::PolishedTuffSlab
            | ItemKind::PolishedTuffStairs
            | ItemKind::PolishedTuffWall
            | ItemKind::TuffBricks
            | ItemKind::TuffBrickSlab
            | ItemKind::TuffBrickStairs
            | ItemKind::TuffBrickWall
            | ItemKind::ChiseledTuffBricks
            | ItemKind::Sulfur
            | ItemKind::PotentSulfur
            | ItemKind::SulfurSlab
            | ItemKind::SulfurStairs
            | ItemKind::SulfurWall
            | ItemKind::PolishedSulfur
            | ItemKind::PolishedSulfurSlab
            | ItemKind::PolishedSulfurStairs
            | ItemKind::PolishedSulfurWall
            | ItemKind::SulfurBricks
            | ItemKind::SulfurBrickSlab
            | ItemKind::SulfurBrickStairs
            | ItemKind::SulfurBrickWall
            | ItemKind::ChiseledSulfur
            | ItemKind::Cinnabar
            | ItemKind::CinnabarSlab
            | ItemKind::CinnabarStairs
            | ItemKind::CinnabarWall
            | ItemKind::PolishedCinnabar
            | ItemKind::PolishedCinnabarSlab
            | ItemKind::PolishedCinnabarStairs
            | ItemKind::PolishedCinnabarWall
            | ItemKind::CinnabarBricks
            | ItemKind::CinnabarBrickSlab
            | ItemKind::CinnabarBrickStairs
            | ItemKind::CinnabarBrickWall
            | ItemKind::ChiseledCinnabar
            | ItemKind::DripstoneBlock
            | ItemKind::Cobblestone
            | ItemKind::Bedrock
            | ItemKind::CoalOre
            | ItemKind::DeepslateCoalOre
            | ItemKind::IronOre
            | ItemKind::DeepslateIronOre
            | ItemKind::CopperOre
            | ItemKind::DeepslateCopperOre
            | ItemKind::GoldOre
            | ItemKind::DeepslateGoldOre
            | ItemKind::RedstoneOre
            | ItemKind::DeepslateRedstoneOre
            | ItemKind::EmeraldOre
            | ItemKind::DeepslateEmeraldOre
            | ItemKind::LapisOre
            | ItemKind::DeepslateLapisOre
            | ItemKind::DiamondOre
            | ItemKind::DeepslateDiamondOre
            | ItemKind::NetherGoldOre
            | ItemKind::NetherQuartzOre
            | ItemKind::AncientDebris
            | ItemKind::Sandstone
            | ItemKind::ChiseledSandstone
            | ItemKind::CutSandstone
            | ItemKind::StoneSlab
            | ItemKind::SmoothStoneSlab
            | ItemKind::SandstoneSlab
            | ItemKind::CutSandstoneSlab
            | ItemKind::PetrifiedOakSlab
            | ItemKind::CobblestoneSlab
            | ItemKind::BrickSlab
            | ItemKind::StoneBrickSlab
            | ItemKind::MudBrickSlab
            | ItemKind::NetherBrickSlab
            | ItemKind::QuartzSlab
            | ItemKind::RedSandstoneSlab
            | ItemKind::CutRedSandstoneSlab
            | ItemKind::PurpurSlab
            | ItemKind::PrismarineSlab
            | ItemKind::PrismarineBrickSlab
            | ItemKind::DarkPrismarineSlab
            | ItemKind::SmoothQuartz
            | ItemKind::SmoothRedSandstone
            | ItemKind::SmoothSandstone
            | ItemKind::SmoothStone
            | ItemKind::Bricks
            | ItemKind::MossyCobblestone
            | ItemKind::Obsidian
            | ItemKind::Furnace
            | ItemKind::Ladder
            | ItemKind::CobblestoneStairs
            | ItemKind::Netherrack
            | ItemKind::Basalt
            | ItemKind::PolishedBasalt
            | ItemKind::SmoothBasalt
            | ItemKind::InfestedStone
            | ItemKind::InfestedCobblestone
            | ItemKind::InfestedStoneBricks
            | ItemKind::InfestedMossyStoneBricks
            | ItemKind::InfestedCrackedStoneBricks
            | ItemKind::InfestedChiseledStoneBricks
            | ItemKind::InfestedDeepslate
            | ItemKind::StoneBricks
            | ItemKind::MossyStoneBricks
            | ItemKind::CrackedStoneBricks
            | ItemKind::ChiseledStoneBricks
            | ItemKind::PackedMud
            | ItemKind::MudBricks
            | ItemKind::DeepslateBricks
            | ItemKind::CrackedDeepslateBricks
            | ItemKind::DeepslateTiles
            | ItemKind::CrackedDeepslateTiles
            | ItemKind::ChiseledDeepslate
            | ItemKind::ReinforcedDeepslate
            | ItemKind::BrickStairs
            | ItemKind::StoneBrickStairs
            | ItemKind::MudBrickStairs
            | ItemKind::NetherBricks
            | ItemKind::CrackedNetherBricks
            | ItemKind::ChiseledNetherBricks
            | ItemKind::NetherBrickFence
            | ItemKind::NetherBrickStairs
            | ItemKind::EndStone
            | ItemKind::EndStoneBricks
            | ItemKind::SandstoneStairs
            | ItemKind::CobblestoneWall
            | ItemKind::MossyCobblestoneWall
            | ItemKind::BrickWall
            | ItemKind::PrismarineWall
            | ItemKind::RedSandstoneWall
            | ItemKind::MossyStoneBrickWall
            | ItemKind::GraniteWall
            | ItemKind::StoneBrickWall
            | ItemKind::MudBrickWall
            | ItemKind::NetherBrickWall
            | ItemKind::AndesiteWall
            | ItemKind::RedNetherBrickWall
            | ItemKind::SandstoneWall
            | ItemKind::EndStoneBrickWall
            | ItemKind::DioriteWall
            | ItemKind::BlackstoneWall
            | ItemKind::PolishedBlackstoneWall
            | ItemKind::PolishedBlackstoneBrickWall
            | ItemKind::CobbledDeepslateWall
            | ItemKind::PolishedDeepslateWall
            | ItemKind::DeepslateBrickWall
            | ItemKind::DeepslateTileWall
            | ItemKind::ChiseledQuartzBlock
            | ItemKind::QuartzBlock
            | ItemKind::QuartzBricks
            | ItemKind::QuartzPillar
            | ItemKind::QuartzStairs
            | ItemKind::Prismarine
            | ItemKind::PrismarineBricks
            | ItemKind::DarkPrismarine
            | ItemKind::PrismarineStairs
            | ItemKind::PrismarineBrickStairs
            | ItemKind::DarkPrismarineStairs
            | ItemKind::SeaLantern
            | ItemKind::RedSandstone
            | ItemKind::ChiseledRedSandstone
            | ItemKind::CutRedSandstone
            | ItemKind::RedSandstoneStairs
            | ItemKind::MagmaBlock
            | ItemKind::RedNetherBricks
            | ItemKind::PolishedGraniteStairs
            | ItemKind::SmoothRedSandstoneStairs
            | ItemKind::MossyStoneBrickStairs
            | ItemKind::PolishedDioriteStairs
            | ItemKind::MossyCobblestoneStairs
            | ItemKind::EndStoneBrickStairs
            | ItemKind::StoneStairs
            | ItemKind::SmoothSandstoneStairs
            | ItemKind::SmoothQuartzStairs
            | ItemKind::GraniteStairs
            | ItemKind::AndesiteStairs
            | ItemKind::RedNetherBrickStairs
            | ItemKind::PolishedAndesiteStairs
            | ItemKind::DioriteStairs
            | ItemKind::CobbledDeepslateStairs
            | ItemKind::PolishedDeepslateStairs
            | ItemKind::DeepslateBrickStairs
            | ItemKind::DeepslateTileStairs
            | ItemKind::PolishedGraniteSlab
            | ItemKind::SmoothRedSandstoneSlab
            | ItemKind::MossyStoneBrickSlab
            | ItemKind::PolishedDioriteSlab
            | ItemKind::MossyCobblestoneSlab
            | ItemKind::EndStoneBrickSlab
            | ItemKind::SmoothSandstoneSlab
            | ItemKind::SmoothQuartzSlab
            | ItemKind::GraniteSlab
            | ItemKind::AndesiteSlab
            | ItemKind::RedNetherBrickSlab
            | ItemKind::PolishedAndesiteSlab
            | ItemKind::DioriteSlab
            | ItemKind::CobbledDeepslateSlab
            | ItemKind::PolishedDeepslateSlab
            | ItemKind::DeepslateBrickSlab
            | ItemKind::DeepslateTileSlab
            | ItemKind::StoneButton
            | ItemKind::PolishedBlackstoneButton
            | ItemKind::StonePressurePlate
            | ItemKind::PolishedBlackstonePressurePlate
            | ItemKind::ClayBall
            | ItemKind::NetherBrick
            | ItemKind::CryingObsidian
            | ItemKind::Blackstone
            | ItemKind::BlackstoneSlab
            | ItemKind::BlackstoneStairs
            | ItemKind::GildedBlackstone
            | ItemKind::PolishedBlackstone
            | ItemKind::PolishedBlackstoneSlab
            | ItemKind::PolishedBlackstoneStairs
            | ItemKind::ChiseledPolishedBlackstone
            | ItemKind::PolishedBlackstoneBricks
            | ItemKind::PolishedBlackstoneBrickSlab
            | ItemKind::PolishedBlackstoneBrickStairs
            | ItemKind::CrackedPolishedBlackstoneBricks
            | ItemKind::PointedDripstone
            | ItemKind::SulfurSpike => ItemCategory::Rocks,

            ItemKind::OakPlanks
            | ItemKind::SprucePlanks
            | ItemKind::BirchPlanks
            | ItemKind::JunglePlanks
            | ItemKind::AcaciaPlanks
            | ItemKind::CherryPlanks
            | ItemKind::DarkOakPlanks
            | ItemKind::PaleOakPlanks
            | ItemKind::MangrovePlanks
            | ItemKind::BambooPlanks
            | ItemKind::CrimsonPlanks
            | ItemKind::WarpedPlanks
            | ItemKind::BambooMosaic
            | ItemKind::OakSapling
            | ItemKind::SpruceSapling
            | ItemKind::BirchSapling
            | ItemKind::JungleSapling
            | ItemKind::AcaciaSapling
            | ItemKind::CherrySapling
            | ItemKind::DarkOakSapling
            | ItemKind::PaleOakSapling
            | ItemKind::MangrovePropagule
            | ItemKind::OakLog
            | ItemKind::SpruceLog
            | ItemKind::BirchLog
            | ItemKind::JungleLog
            | ItemKind::AcaciaLog
            | ItemKind::CherryLog
            | ItemKind::PaleOakLog
            | ItemKind::DarkOakLog
            | ItemKind::MangroveLog
            | ItemKind::MangroveRoots
            | ItemKind::MuddyMangroveRoots
            | ItemKind::CrimsonStem
            | ItemKind::WarpedStem
            | ItemKind::BambooBlock
            | ItemKind::StrippedOakLog
            | ItemKind::StrippedSpruceLog
            | ItemKind::StrippedBirchLog
            | ItemKind::StrippedJungleLog
            | ItemKind::StrippedAcaciaLog
            | ItemKind::StrippedCherryLog
            | ItemKind::StrippedDarkOakLog
            | ItemKind::StrippedPaleOakLog
            | ItemKind::StrippedMangroveLog
            | ItemKind::StrippedCrimsonStem
            | ItemKind::StrippedWarpedStem
            | ItemKind::StrippedOakWood
            | ItemKind::StrippedSpruceWood
            | ItemKind::StrippedBirchWood
            | ItemKind::StrippedJungleWood
            | ItemKind::StrippedAcaciaWood
            | ItemKind::StrippedCherryWood
            | ItemKind::StrippedDarkOakWood
            | ItemKind::StrippedPaleOakWood
            | ItemKind::StrippedMangroveWood
            | ItemKind::StrippedCrimsonHyphae
            | ItemKind::StrippedWarpedHyphae
            | ItemKind::StrippedBambooBlock
            | ItemKind::OakWood
            | ItemKind::SpruceWood
            | ItemKind::BirchWood
            | ItemKind::JungleWood
            | ItemKind::AcaciaWood
            | ItemKind::CherryWood
            | ItemKind::PaleOakWood
            | ItemKind::DarkOakWood
            | ItemKind::MangroveWood
            | ItemKind::CrimsonHyphae
            | ItemKind::WarpedHyphae
            | ItemKind::OakLeaves
            | ItemKind::SpruceLeaves
            | ItemKind::BirchLeaves
            | ItemKind::JungleLeaves
            | ItemKind::AcaciaLeaves
            | ItemKind::CherryLeaves
            | ItemKind::DarkOakLeaves
            | ItemKind::PaleOakLeaves
            | ItemKind::MangroveLeaves
            | ItemKind::AzaleaLeaves
            | ItemKind::FloweringAzaleaLeaves
            | ItemKind::Bamboo
            | ItemKind::OakSlab
            | ItemKind::SpruceSlab
            | ItemKind::BirchSlab
            | ItemKind::JungleSlab
            | ItemKind::AcaciaSlab
            | ItemKind::CherrySlab
            | ItemKind::DarkOakSlab
            | ItemKind::PaleOakSlab
            | ItemKind::MangroveSlab
            | ItemKind::BambooSlab
            | ItemKind::BambooMosaicSlab
            | ItemKind::CrimsonSlab
            | ItemKind::WarpedSlab
            | ItemKind::AcaciaShelf
            | ItemKind::BambooShelf
            | ItemKind::BirchShelf
            | ItemKind::CherryShelf
            | ItemKind::CrimsonShelf
            | ItemKind::DarkOakShelf
            | ItemKind::JungleShelf
            | ItemKind::MangroveShelf
            | ItemKind::OakShelf
            | ItemKind::PaleOakShelf
            | ItemKind::SpruceShelf
            | ItemKind::WarpedShelf
            | ItemKind::Bookshelf
            | ItemKind::ChiseledBookshelf
            | ItemKind::OakFence
            | ItemKind::SpruceFence
            | ItemKind::BirchFence
            | ItemKind::JungleFence
            | ItemKind::AcaciaFence
            | ItemKind::CherryFence
            | ItemKind::DarkOakFence
            | ItemKind::PaleOakFence
            | ItemKind::MangroveFence
            | ItemKind::BambooFence
            | ItemKind::CrimsonFence
            | ItemKind::WarpedFence
            | ItemKind::OakStairs
            | ItemKind::SpruceStairs
            | ItemKind::BirchStairs
            | ItemKind::JungleStairs
            | ItemKind::AcaciaStairs
            | ItemKind::CherryStairs
            | ItemKind::DarkOakStairs
            | ItemKind::PaleOakStairs
            | ItemKind::MangroveStairs
            | ItemKind::BambooStairs
            | ItemKind::BambooMosaicStairs
            | ItemKind::CrimsonStairs
            | ItemKind::WarpedStairs
            | ItemKind::OakButton
            | ItemKind::SpruceButton
            | ItemKind::BirchButton
            | ItemKind::JungleButton
            | ItemKind::AcaciaButton
            | ItemKind::CherryButton
            | ItemKind::DarkOakButton
            | ItemKind::PaleOakButton
            | ItemKind::MangroveButton
            | ItemKind::BambooButton
            | ItemKind::CrimsonButton
            | ItemKind::WarpedButton
            | ItemKind::OakPressurePlate
            | ItemKind::SprucePressurePlate
            | ItemKind::BirchPressurePlate
            | ItemKind::JunglePressurePlate
            | ItemKind::AcaciaPressurePlate
            | ItemKind::CherryPressurePlate
            | ItemKind::DarkOakPressurePlate
            | ItemKind::PaleOakPressurePlate
            | ItemKind::MangrovePressurePlate
            | ItemKind::BambooPressurePlate
            | ItemKind::CrimsonPressurePlate
            | ItemKind::WarpedPressurePlate
            | ItemKind::OakDoor
            | ItemKind::SpruceDoor
            | ItemKind::BirchDoor
            | ItemKind::JungleDoor
            | ItemKind::AcaciaDoor
            | ItemKind::CherryDoor
            | ItemKind::DarkOakDoor
            | ItemKind::PaleOakDoor
            | ItemKind::MangroveDoor
            | ItemKind::BambooDoor
            | ItemKind::CrimsonDoor
            | ItemKind::WarpedDoor
            | ItemKind::OakTrapdoor
            | ItemKind::SpruceTrapdoor
            | ItemKind::BirchTrapdoor
            | ItemKind::JungleTrapdoor
            | ItemKind::AcaciaTrapdoor
            | ItemKind::CherryTrapdoor
            | ItemKind::DarkOakTrapdoor
            | ItemKind::PaleOakTrapdoor
            | ItemKind::MangroveTrapdoor
            | ItemKind::BambooTrapdoor
            | ItemKind::CrimsonTrapdoor
            | ItemKind::WarpedTrapdoor
            | ItemKind::OakFenceGate
            | ItemKind::SpruceFenceGate
            | ItemKind::BirchFenceGate
            | ItemKind::JungleFenceGate
            | ItemKind::AcaciaFenceGate
            | ItemKind::CherryFenceGate
            | ItemKind::DarkOakFenceGate
            | ItemKind::PaleOakFenceGate
            | ItemKind::MangroveFenceGate
            | ItemKind::BambooFenceGate
            | ItemKind::CrimsonFenceGate
            | ItemKind::WarpedFenceGate
            | ItemKind::OakBoat
            | ItemKind::OakChestBoat
            | ItemKind::SpruceBoat
            | ItemKind::SpruceChestBoat
            | ItemKind::BirchBoat
            | ItemKind::BirchChestBoat
            | ItemKind::JungleBoat
            | ItemKind::JungleChestBoat
            | ItemKind::AcaciaBoat
            | ItemKind::AcaciaChestBoat
            | ItemKind::CherryBoat
            | ItemKind::CherryChestBoat
            | ItemKind::DarkOakBoat
            | ItemKind::DarkOakChestBoat
            | ItemKind::PaleOakBoat
            | ItemKind::PaleOakChestBoat
            | ItemKind::MangroveBoat
            | ItemKind::MangroveChestBoat
            | ItemKind::BambooRaft
            | ItemKind::BambooChestRaft
            | ItemKind::Bowl
            | ItemKind::Stick
            | ItemKind::OakSign
            | ItemKind::SpruceSign
            | ItemKind::BirchSign
            | ItemKind::JungleSign
            | ItemKind::AcaciaSign
            | ItemKind::CherrySign
            | ItemKind::DarkOakSign
            | ItemKind::PaleOakSign
            | ItemKind::MangroveSign
            | ItemKind::BambooSign
            | ItemKind::CrimsonSign
            | ItemKind::WarpedSign
            | ItemKind::OakHangingSign
            | ItemKind::SpruceHangingSign
            | ItemKind::BirchHangingSign
            | ItemKind::JungleHangingSign
            | ItemKind::AcaciaHangingSign
            | ItemKind::CherryHangingSign
            | ItemKind::DarkOakHangingSign
            | ItemKind::PaleOakHangingSign
            | ItemKind::MangroveHangingSign
            | ItemKind::BambooHangingSign
            | ItemKind::CrimsonHangingSign
            | ItemKind::WarpedHangingSign => ItemCategory::Wood,

            ItemKind::GrassBlock
            | ItemKind::Dirt
            | ItemKind::CoarseDirt
            | ItemKind::Podzol
            | ItemKind::RootedDirt
            | ItemKind::Mud
            | ItemKind::Farmland
            | ItemKind::DirtPath
            | ItemKind::Mycelium
            | ItemKind::CrimsonNylium
            | ItemKind::WarpedNylium
            | ItemKind::SoulSand
            | ItemKind::SoulSoil
            | ItemKind::Sand
            | ItemKind::SuspiciousSand
            | ItemKind::RedSand
            | ItemKind::Gravel
            | ItemKind::SuspiciousGravel
            | ItemKind::Clay
            | ItemKind::Snow
            | ItemKind::SnowBlock
            | ItemKind::Ice
            | ItemKind::PackedIce
            | ItemKind::BlueIce
            | ItemKind::ShortGrass
            | ItemKind::Fern
            | ItemKind::TallGrass
            | ItemKind::LargeFern
            | ItemKind::Bush
            | ItemKind::DeadBush
            | ItemKind::FireflyBush
            | ItemKind::ShortDryGrass
            | ItemKind::TallDryGrass
            | ItemKind::Azalea
            | ItemKind::FloweringAzalea
            | ItemKind::MossBlock
            | ItemKind::MossCarpet
            | ItemKind::PaleMossBlock
            | ItemKind::PaleMossCarpet
            | ItemKind::PaleHangingMoss
            | ItemKind::GlowLichen
            | ItemKind::HangingRoots
            | ItemKind::BigDripleaf
            | ItemKind::SmallDripleaf
            | ItemKind::SugarCane
            | ItemKind::Cactus
            | ItemKind::CactusFlower
            | ItemKind::Vine
            | ItemKind::LilyPad
            | ItemKind::Seagrass
            | ItemKind::SeaPickle
            | ItemKind::BrownMushroom
            | ItemKind::RedMushroom
            | ItemKind::CrimsonFungus
            | ItemKind::WarpedFungus
            | ItemKind::CrimsonRoots
            | ItemKind::WarpedRoots
            | ItemKind::NetherSprouts
            | ItemKind::WeepingVines
            | ItemKind::TwistingVines
            | ItemKind::Dandelion
            | ItemKind::GoldenDandelion
            | ItemKind::OpenEyeblossom
            | ItemKind::ClosedEyeblossom
            | ItemKind::Poppy
            | ItemKind::BlueOrchid
            | ItemKind::Allium
            | ItemKind::AzureBluet
            | ItemKind::RedTulip
            | ItemKind::OrangeTulip
            | ItemKind::WhiteTulip
            | ItemKind::PinkTulip
            | ItemKind::OxeyeDaisy
            | ItemKind::Cornflower
            | ItemKind::LilyOfTheValley
            | ItemKind::WitherRose
            | ItemKind::Torchflower
            | ItemKind::PitcherPlant
            | ItemKind::SporeBlossom
            | ItemKind::PinkPetals
            | ItemKind::Wildflowers
            | ItemKind::LeafLitter
            | ItemKind::Sunflower
            | ItemKind::Lilac
            | ItemKind::RoseBush
            | ItemKind::Peony
            | ItemKind::ChorusPlant
            | ItemKind::ChorusFlower
            | ItemKind::Kelp
            | ItemKind::BrownMushroomBlock
            | ItemKind::RedMushroomBlock
            | ItemKind::MushroomStem
            | ItemKind::TubeCoral
            | ItemKind::BrainCoral
            | ItemKind::BubbleCoral
            | ItemKind::FireCoral
            | ItemKind::HornCoral
            | ItemKind::DeadTubeCoral
            | ItemKind::DeadBrainCoral
            | ItemKind::DeadBubbleCoral
            | ItemKind::DeadFireCoral
            | ItemKind::DeadHornCoral
            | ItemKind::TubeCoralBlock
            | ItemKind::BrainCoralBlock
            | ItemKind::BubbleCoralBlock
            | ItemKind::FireCoralBlock
            | ItemKind::HornCoralBlock
            | ItemKind::DeadTubeCoralBlock
            | ItemKind::DeadBrainCoralBlock
            | ItemKind::DeadBubbleCoralBlock
            | ItemKind::DeadFireCoralBlock
            | ItemKind::DeadHornCoralBlock
            | ItemKind::TubeCoralFan
            | ItemKind::BrainCoralFan
            | ItemKind::BubbleCoralFan
            | ItemKind::FireCoralFan
            | ItemKind::HornCoralFan
            | ItemKind::DeadTubeCoralFan
            | ItemKind::DeadBrainCoralFan
            | ItemKind::DeadBubbleCoralFan
            | ItemKind::DeadFireCoralFan
            | ItemKind::DeadHornCoralFan => ItemCategory::Nature,

            ItemKind::Anvil
            | ItemKind::ChippedAnvil
            | ItemKind::DamagedAnvil
            | ItemKind::Saddle
            | ItemKind::WhiteHarness
            | ItemKind::OrangeHarness
            | ItemKind::MagentaHarness
            | ItemKind::LightBlueHarness
            | ItemKind::YellowHarness
            | ItemKind::LimeHarness
            | ItemKind::PinkHarness
            | ItemKind::GrayHarness
            | ItemKind::LightGrayHarness
            | ItemKind::CyanHarness
            | ItemKind::PurpleHarness
            | ItemKind::BlueHarness
            | ItemKind::BrownHarness
            | ItemKind::GreenHarness
            | ItemKind::RedHarness
            | ItemKind::BlackHarness
            | ItemKind::Minecart
            | ItemKind::ChestMinecart
            | ItemKind::FurnaceMinecart
            | ItemKind::TntMinecart
            | ItemKind::HopperMinecart
            | ItemKind::CarrotOnAStick
            | ItemKind::WarpedFungusOnAStick
            | ItemKind::Elytra
            | ItemKind::TurtleHelmet
            | ItemKind::WolfArmor
            | ItemKind::FlintAndSteel
            | ItemKind::Bow
            | ItemKind::Arrow
            | ItemKind::WoodenSword
            | ItemKind::WoodenShovel
            | ItemKind::WoodenPickaxe
            | ItemKind::WoodenAxe
            | ItemKind::WoodenHoe
            | ItemKind::CopperSword
            | ItemKind::CopperShovel
            | ItemKind::CopperPickaxe
            | ItemKind::CopperAxe
            | ItemKind::CopperHoe
            | ItemKind::StoneSword
            | ItemKind::StoneShovel
            | ItemKind::StonePickaxe
            | ItemKind::StoneAxe
            | ItemKind::StoneHoe
            | ItemKind::GoldenSword
            | ItemKind::GoldenShovel
            | ItemKind::GoldenPickaxe
            | ItemKind::GoldenAxe
            | ItemKind::GoldenHoe
            | ItemKind::IronSword
            | ItemKind::IronShovel
            | ItemKind::IronPickaxe
            | ItemKind::IronAxe
            | ItemKind::IronHoe
            | ItemKind::DiamondSword
            | ItemKind::DiamondShovel
            | ItemKind::DiamondPickaxe
            | ItemKind::DiamondAxe
            | ItemKind::DiamondHoe
            | ItemKind::NetheriteSword
            | ItemKind::NetheriteShovel
            | ItemKind::NetheritePickaxe
            | ItemKind::NetheriteAxe
            | ItemKind::NetheriteHoe
            | ItemKind::LeatherHelmet
            | ItemKind::LeatherChestplate
            | ItemKind::LeatherLeggings
            | ItemKind::LeatherBoots
            | ItemKind::CopperHelmet
            | ItemKind::CopperChestplate
            | ItemKind::CopperLeggings
            | ItemKind::CopperBoots
            | ItemKind::ChainmailHelmet
            | ItemKind::ChainmailChestplate
            | ItemKind::ChainmailLeggings
            | ItemKind::ChainmailBoots
            | ItemKind::IronHelmet
            | ItemKind::IronChestplate
            | ItemKind::IronLeggings
            | ItemKind::IronBoots
            | ItemKind::DiamondHelmet
            | ItemKind::DiamondChestplate
            | ItemKind::DiamondLeggings
            | ItemKind::DiamondBoots
            | ItemKind::GoldenHelmet
            | ItemKind::GoldenChestplate
            | ItemKind::GoldenLeggings
            | ItemKind::GoldenBoots
            | ItemKind::NetheriteHelmet
            | ItemKind::NetheriteChestplate
            | ItemKind::NetheriteLeggings
            | ItemKind::NetheriteBoots
            | ItemKind::Bucket
            | ItemKind::WaterBucket
            | ItemKind::LavaBucket
            | ItemKind::PowderSnowBucket
            | ItemKind::PufferfishBucket
            | ItemKind::SalmonBucket
            | ItemKind::CodBucket
            | ItemKind::TropicalFishBucket
            | ItemKind::AxolotlBucket
            | ItemKind::SulfurCubeBucket
            | ItemKind::TadpoleBucket
            | ItemKind::Compass
            | ItemKind::RecoveryCompass
            | ItemKind::Bundle
            | ItemKind::WhiteBundle
            | ItemKind::OrangeBundle
            | ItemKind::MagentaBundle
            | ItemKind::LightBlueBundle
            | ItemKind::YellowBundle
            | ItemKind::LimeBundle
            | ItemKind::PinkBundle
            | ItemKind::GrayBundle
            | ItemKind::LightGrayBundle
            | ItemKind::CyanBundle
            | ItemKind::PurpleBundle
            | ItemKind::BlueBundle
            | ItemKind::BrownBundle
            | ItemKind::GreenBundle
            | ItemKind::RedBundle
            | ItemKind::BlackBundle
            | ItemKind::FishingRod
            | ItemKind::Clock
            | ItemKind::Spyglass
            | ItemKind::FilledMap
            | ItemKind::Shears
            | ItemKind::FireCharge
            | ItemKind::WindCharge
            | ItemKind::Mace
            | ItemKind::Map
            | ItemKind::FireworkRocket
            | ItemKind::EnchantedBook
            | ItemKind::CopperHorseArmor
            | ItemKind::IronHorseArmor
            | ItemKind::GoldenHorseArmor
            | ItemKind::DiamondHorseArmor
            | ItemKind::NetheriteHorseArmor
            | ItemKind::LeatherHorseArmor
            | ItemKind::Lead
            | ItemKind::NameTag
            | ItemKind::SpectralArrow
            | ItemKind::TippedArrow
            | ItemKind::Shield
            | ItemKind::WoodenSpear
            | ItemKind::StoneSpear
            | ItemKind::CopperSpear
            | ItemKind::IronSpear
            | ItemKind::GoldenSpear
            | ItemKind::DiamondSpear
            | ItemKind::NetheriteSpear
            | ItemKind::TotemOfUndying
            | ItemKind::Trident
            | ItemKind::IronNautilusArmor
            | ItemKind::GoldenNautilusArmor
            | ItemKind::DiamondNautilusArmor
            | ItemKind::NetheriteNautilusArmor
            | ItemKind::CopperNautilusArmor
            | ItemKind::Crossbow
            | ItemKind::GoatHorn
            | ItemKind::Brush => ItemCategory::Tools,

            ItemKind::CoalBlock
            | ItemKind::RawIronBlock
            | ItemKind::RawCopperBlock
            | ItemKind::RawGoldBlock
            | ItemKind::AmethystBlock
            | ItemKind::BuddingAmethyst
            | ItemKind::IronBlock
            | ItemKind::CopperBlock
            | ItemKind::ExposedCopper
            | ItemKind::WeatheredCopper
            | ItemKind::OxidizedCopper
            | ItemKind::WaxedCopperBlock
            | ItemKind::WaxedExposedCopper
            | ItemKind::WaxedWeatheredCopper
            | ItemKind::WaxedOxidizedCopper
            | ItemKind::GoldBlock
            | ItemKind::DiamondBlock
            | ItemKind::NetheriteBlock
            | ItemKind::ChiseledCopper
            | ItemKind::ExposedChiseledCopper
            | ItemKind::WeatheredChiseledCopper
            | ItemKind::OxidizedChiseledCopper
            | ItemKind::WaxedChiseledCopper
            | ItemKind::WaxedExposedChiseledCopper
            | ItemKind::WaxedWeatheredChiseledCopper
            | ItemKind::WaxedOxidizedChiseledCopper
            | ItemKind::CutCopper
            | ItemKind::ExposedCutCopper
            | ItemKind::WeatheredCutCopper
            | ItemKind::OxidizedCutCopper
            | ItemKind::WaxedCutCopper
            | ItemKind::WaxedExposedCutCopper
            | ItemKind::WaxedWeatheredCutCopper
            | ItemKind::WaxedOxidizedCutCopper
            | ItemKind::CutCopperStairs
            | ItemKind::ExposedCutCopperStairs
            | ItemKind::WeatheredCutCopperStairs
            | ItemKind::OxidizedCutCopperStairs
            | ItemKind::WaxedCutCopperStairs
            | ItemKind::WaxedExposedCutCopperStairs
            | ItemKind::WaxedWeatheredCutCopperStairs
            | ItemKind::WaxedOxidizedCutCopperStairs
            | ItemKind::CutCopperSlab
            | ItemKind::ExposedCutCopperSlab
            | ItemKind::WeatheredCutCopperSlab
            | ItemKind::OxidizedCutCopperSlab
            | ItemKind::WaxedCutCopperSlab
            | ItemKind::WaxedExposedCutCopperSlab
            | ItemKind::WaxedWeatheredCutCopperSlab
            | ItemKind::WaxedOxidizedCutCopperSlab
            | ItemKind::Sponge
            | ItemKind::WetSponge
            | ItemKind::Glass
            | ItemKind::TintedGlass
            | ItemKind::LapisBlock
            | ItemKind::Cobweb
            | ItemKind::WhiteWool
            | ItemKind::OrangeWool
            | ItemKind::MagentaWool
            | ItemKind::LightBlueWool
            | ItemKind::YellowWool
            | ItemKind::LimeWool
            | ItemKind::PinkWool
            | ItemKind::GrayWool
            | ItemKind::LightGrayWool
            | ItemKind::CyanWool
            | ItemKind::PurpleWool
            | ItemKind::BlueWool
            | ItemKind::BrownWool
            | ItemKind::GreenWool
            | ItemKind::RedWool
            | ItemKind::BlackWool
            | ItemKind::DecoratedPot
            | ItemKind::Torch
            | ItemKind::EndRod
            | ItemKind::PurpurBlock
            | ItemKind::PurpurPillar
            | ItemKind::PurpurStairs
            | ItemKind::Chest
            | ItemKind::CraftingTable
            | ItemKind::Jukebox
            | ItemKind::CarvedPumpkin
            | ItemKind::JackOLantern
            | ItemKind::SoulTorch
            | ItemKind::CopperTorch
            | ItemKind::Glowstone
            | ItemKind::IronBars
            | ItemKind::CopperBars
            | ItemKind::ExposedCopperBars
            | ItemKind::WeatheredCopperBars
            | ItemKind::OxidizedCopperBars
            | ItemKind::WaxedCopperBars
            | ItemKind::WaxedExposedCopperBars
            | ItemKind::WaxedWeatheredCopperBars
            | ItemKind::WaxedOxidizedCopperBars
            | ItemKind::IronChain
            | ItemKind::CopperChain
            | ItemKind::ExposedCopperChain
            | ItemKind::WeatheredCopperChain
            | ItemKind::OxidizedCopperChain
            | ItemKind::WaxedCopperChain
            | ItemKind::WaxedExposedCopperChain
            | ItemKind::WaxedWeatheredCopperChain
            | ItemKind::WaxedOxidizedCopperChain
            | ItemKind::GlassPane
            | ItemKind::ResinClump
            | ItemKind::ResinBlock
            | ItemKind::ResinBricks
            | ItemKind::ResinBrickStairs
            | ItemKind::ResinBrickSlab
            | ItemKind::ResinBrickWall
            | ItemKind::ChiseledResinBricks
            | ItemKind::Sculk
            | ItemKind::SculkVein
            | ItemKind::SculkCatalyst
            | ItemKind::SculkShrieker
            | ItemKind::EnchantingTable
            | ItemKind::EnderChest
            | ItemKind::EmeraldBlock
            | ItemKind::Beacon
            | ItemKind::WhiteTerracotta
            | ItemKind::OrangeTerracotta
            | ItemKind::MagentaTerracotta
            | ItemKind::LightBlueTerracotta
            | ItemKind::YellowTerracotta
            | ItemKind::LimeTerracotta
            | ItemKind::PinkTerracotta
            | ItemKind::GrayTerracotta
            | ItemKind::LightGrayTerracotta
            | ItemKind::CyanTerracotta
            | ItemKind::PurpleTerracotta
            | ItemKind::BlueTerracotta
            | ItemKind::BrownTerracotta
            | ItemKind::GreenTerracotta
            | ItemKind::RedTerracotta
            | ItemKind::BlackTerracotta
            | ItemKind::HayBlock
            | ItemKind::WhiteCarpet
            | ItemKind::OrangeCarpet
            | ItemKind::MagentaCarpet
            | ItemKind::LightBlueCarpet
            | ItemKind::YellowCarpet
            | ItemKind::LimeCarpet
            | ItemKind::PinkCarpet
            | ItemKind::GrayCarpet
            | ItemKind::LightGrayCarpet
            | ItemKind::CyanCarpet
            | ItemKind::PurpleCarpet
            | ItemKind::BlueCarpet
            | ItemKind::BrownCarpet
            | ItemKind::GreenCarpet
            | ItemKind::RedCarpet
            | ItemKind::BlackCarpet
            | ItemKind::Terracotta
            | ItemKind::WhiteStainedGlass
            | ItemKind::OrangeStainedGlass
            | ItemKind::MagentaStainedGlass
            | ItemKind::LightBlueStainedGlass
            | ItemKind::YellowStainedGlass
            | ItemKind::LimeStainedGlass
            | ItemKind::PinkStainedGlass
            | ItemKind::GrayStainedGlass
            | ItemKind::LightGrayStainedGlass
            | ItemKind::CyanStainedGlass
            | ItemKind::PurpleStainedGlass
            | ItemKind::BlueStainedGlass
            | ItemKind::BrownStainedGlass
            | ItemKind::GreenStainedGlass
            | ItemKind::RedStainedGlass
            | ItemKind::BlackStainedGlass
            | ItemKind::WhiteStainedGlassPane
            | ItemKind::OrangeStainedGlassPane
            | ItemKind::MagentaStainedGlassPane
            | ItemKind::LightBlueStainedGlassPane
            | ItemKind::YellowStainedGlassPane
            | ItemKind::LimeStainedGlassPane
            | ItemKind::PinkStainedGlassPane
            | ItemKind::GrayStainedGlassPane
            | ItemKind::LightGrayStainedGlassPane
            | ItemKind::CyanStainedGlassPane
            | ItemKind::PurpleStainedGlassPane
            | ItemKind::BlueStainedGlassPane
            | ItemKind::BrownStainedGlassPane
            | ItemKind::GreenStainedGlassPane
            | ItemKind::RedStainedGlassPane
            | ItemKind::BlackStainedGlassPane
            | ItemKind::NetherWartBlock
            | ItemKind::WarpedWartBlock
            | ItemKind::BoneBlock
            | ItemKind::ShulkerBox
            | ItemKind::WhiteShulkerBox
            | ItemKind::OrangeShulkerBox
            | ItemKind::MagentaShulkerBox
            | ItemKind::LightBlueShulkerBox
            | ItemKind::YellowShulkerBox
            | ItemKind::LimeShulkerBox
            | ItemKind::PinkShulkerBox
            | ItemKind::GrayShulkerBox
            | ItemKind::LightGrayShulkerBox
            | ItemKind::CyanShulkerBox
            | ItemKind::PurpleShulkerBox
            | ItemKind::BlueShulkerBox
            | ItemKind::BrownShulkerBox
            | ItemKind::GreenShulkerBox
            | ItemKind::RedShulkerBox
            | ItemKind::BlackShulkerBox
            | ItemKind::WhiteGlazedTerracotta
            | ItemKind::OrangeGlazedTerracotta
            | ItemKind::MagentaGlazedTerracotta
            | ItemKind::LightBlueGlazedTerracotta
            | ItemKind::YellowGlazedTerracotta
            | ItemKind::LimeGlazedTerracotta
            | ItemKind::PinkGlazedTerracotta
            | ItemKind::GrayGlazedTerracotta
            | ItemKind::LightGrayGlazedTerracotta
            | ItemKind::CyanGlazedTerracotta
            | ItemKind::PurpleGlazedTerracotta
            | ItemKind::BlueGlazedTerracotta
            | ItemKind::BrownGlazedTerracotta
            | ItemKind::GreenGlazedTerracotta
            | ItemKind::RedGlazedTerracotta
            | ItemKind::BlackGlazedTerracotta
            | ItemKind::WhiteConcrete
            | ItemKind::OrangeConcrete
            | ItemKind::MagentaConcrete
            | ItemKind::LightBlueConcrete
            | ItemKind::YellowConcrete
            | ItemKind::LimeConcrete
            | ItemKind::PinkConcrete
            | ItemKind::GrayConcrete
            | ItemKind::LightGrayConcrete
            | ItemKind::CyanConcrete
            | ItemKind::PurpleConcrete
            | ItemKind::BlueConcrete
            | ItemKind::BrownConcrete
            | ItemKind::GreenConcrete
            | ItemKind::RedConcrete
            | ItemKind::BlackConcrete
            | ItemKind::WhiteConcretePowder
            | ItemKind::OrangeConcretePowder
            | ItemKind::MagentaConcretePowder
            | ItemKind::LightBlueConcretePowder
            | ItemKind::YellowConcretePowder
            | ItemKind::LimeConcretePowder
            | ItemKind::PinkConcretePowder
            | ItemKind::GrayConcretePowder
            | ItemKind::LightGrayConcretePowder
            | ItemKind::CyanConcretePowder
            | ItemKind::PurpleConcretePowder
            | ItemKind::BlueConcretePowder
            | ItemKind::BrownConcretePowder
            | ItemKind::GreenConcretePowder
            | ItemKind::RedConcretePowder
            | ItemKind::BlackConcretePowder
            | ItemKind::Conduit
            | ItemKind::Scaffolding
            | ItemKind::Redstone
            | ItemKind::RedstoneTorch
            | ItemKind::RedstoneBlock
            | ItemKind::Repeater
            | ItemKind::Comparator
            | ItemKind::Piston
            | ItemKind::StickyPiston
            | ItemKind::SlimeBlock
            | ItemKind::HoneyBlock
            | ItemKind::Observer
            | ItemKind::Hopper
            | ItemKind::Dispenser
            | ItemKind::Dropper
            | ItemKind::Lectern
            | ItemKind::Target
            | ItemKind::Lever
            | ItemKind::LightningRod
            | ItemKind::ExposedLightningRod
            | ItemKind::WeatheredLightningRod
            | ItemKind::OxidizedLightningRod
            | ItemKind::WaxedLightningRod
            | ItemKind::WaxedExposedLightningRod
            | ItemKind::WaxedWeatheredLightningRod
            | ItemKind::WaxedOxidizedLightningRod
            | ItemKind::DaylightDetector
            | ItemKind::SculkSensor
            | ItemKind::CalibratedSculkSensor
            | ItemKind::TripwireHook
            | ItemKind::TrappedChest
            | ItemKind::Tnt
            | ItemKind::RedstoneLamp
            | ItemKind::NoteBlock
            | ItemKind::LightWeightedPressurePlate
            | ItemKind::HeavyWeightedPressurePlate
            | ItemKind::IronDoor
            | ItemKind::CopperDoor
            | ItemKind::ExposedCopperDoor
            | ItemKind::WeatheredCopperDoor
            | ItemKind::OxidizedCopperDoor
            | ItemKind::WaxedCopperDoor
            | ItemKind::WaxedExposedCopperDoor
            | ItemKind::WaxedWeatheredCopperDoor
            | ItemKind::WaxedOxidizedCopperDoor
            | ItemKind::IronTrapdoor
            | ItemKind::CopperTrapdoor
            | ItemKind::ExposedCopperTrapdoor
            | ItemKind::WeatheredCopperTrapdoor
            | ItemKind::OxidizedCopperTrapdoor
            | ItemKind::WaxedCopperTrapdoor
            | ItemKind::WaxedExposedCopperTrapdoor
            | ItemKind::WaxedWeatheredCopperTrapdoor
            | ItemKind::WaxedOxidizedCopperTrapdoor
            | ItemKind::PoweredRail
            | ItemKind::DetectorRail
            | ItemKind::Rail
            | ItemKind::ActivatorRail
            | ItemKind::PhantomMembrane
            | ItemKind::TurtleScute
            | ItemKind::ArmadilloScute
            | ItemKind::Coal
            | ItemKind::Charcoal
            | ItemKind::Diamond
            | ItemKind::Emerald
            | ItemKind::LapisLazuli
            | ItemKind::Quartz
            | ItemKind::AmethystShard
            | ItemKind::RawIron
            | ItemKind::IronIngot
            | ItemKind::RawCopper
            | ItemKind::CopperIngot
            | ItemKind::RawGold
            | ItemKind::GoldIngot
            | ItemKind::NetheriteIngot
            | ItemKind::NetheriteScrap
            | ItemKind::WheatSeeds
            | ItemKind::Flint
            | ItemKind::Snowball
            | ItemKind::Leather
            | ItemKind::Brick
            | ItemKind::DriedKelpBlock
            | ItemKind::Paper
            | ItemKind::Book
            | ItemKind::SlimeBall
            | ItemKind::GlowstoneDust
            | ItemKind::InkSac
            | ItemKind::GlowInkSac
            | ItemKind::CocoaBeans
            | ItemKind::WhiteDye
            | ItemKind::OrangeDye
            | ItemKind::MagentaDye
            | ItemKind::LightBlueDye
            | ItemKind::YellowDye
            | ItemKind::LimeDye
            | ItemKind::PinkDye
            | ItemKind::GrayDye
            | ItemKind::LightGrayDye
            | ItemKind::CyanDye
            | ItemKind::PurpleDye
            | ItemKind::BlueDye
            | ItemKind::BrownDye
            | ItemKind::GreenDye
            | ItemKind::RedDye
            | ItemKind::BlackDye
            | ItemKind::BoneMeal
            | ItemKind::Bone
            | ItemKind::Sugar
            | ItemKind::WhiteBed
            | ItemKind::OrangeBed
            | ItemKind::MagentaBed
            | ItemKind::LightBlueBed
            | ItemKind::YellowBed
            | ItemKind::LimeBed
            | ItemKind::PinkBed
            | ItemKind::GrayBed
            | ItemKind::LightGrayBed
            | ItemKind::CyanBed
            | ItemKind::PurpleBed
            | ItemKind::BlueBed
            | ItemKind::BrownBed
            | ItemKind::GreenBed
            | ItemKind::RedBed
            | ItemKind::BlackBed
            | ItemKind::Crafter
            | ItemKind::PumpkinSeeds
            | ItemKind::MelonSeeds
            | ItemKind::EnderPearl
            | ItemKind::BlazeRod
            | ItemKind::GhastTear
            | ItemKind::GoldNugget
            | ItemKind::NetherWart
            | ItemKind::GlassBottle
            | ItemKind::Potion
            | ItemKind::SpiderEye
            | ItemKind::FermentedSpiderEye
            | ItemKind::BlazePowder
            | ItemKind::MagmaCream
            | ItemKind::BrewingStand
            | ItemKind::Cauldron
            | ItemKind::EnderEye
            | ItemKind::GlisteringMelonSlice
            | ItemKind::ExperienceBottle
            | ItemKind::WritableBook
            | ItemKind::BreezeRod
            | ItemKind::NetherStar
            | ItemKind::FireworkStar
            | ItemKind::ResinBrick
            | ItemKind::PrismarineShard
            | ItemKind::PrismarineCrystals
            | ItemKind::RabbitFoot
            | ItemKind::RabbitHide
            | ItemKind::WhiteBanner
            | ItemKind::OrangeBanner
            | ItemKind::MagentaBanner
            | ItemKind::LightBlueBanner
            | ItemKind::YellowBanner
            | ItemKind::LimeBanner
            | ItemKind::PinkBanner
            | ItemKind::GrayBanner
            | ItemKind::LightGrayBanner
            | ItemKind::CyanBanner
            | ItemKind::PurpleBanner
            | ItemKind::BlueBanner
            | ItemKind::BrownBanner
            | ItemKind::GreenBanner
            | ItemKind::RedBanner
            | ItemKind::BlackBanner
            | ItemKind::PoppedChorusFruit
            | ItemKind::TorchflowerSeeds
            | ItemKind::PitcherPod
            | ItemKind::BeetrootSeeds
            | ItemKind::DragonBreath
            | ItemKind::SplashPotion
            | ItemKind::LingeringPotion
            | ItemKind::ShulkerShell
            | ItemKind::IronNugget
            | ItemKind::CopperNugget
            | ItemKind::NautilusShell
            | ItemKind::HeartOfTheSea
            | ItemKind::Loom
            | ItemKind::FlowerBannerPattern
            | ItemKind::CreeperBannerPattern
            | ItemKind::SkullBannerPattern
            | ItemKind::MojangBannerPattern
            | ItemKind::GlobeBannerPattern
            | ItemKind::PiglinBannerPattern
            | ItemKind::FlowBannerPattern
            | ItemKind::GusterBannerPattern
            | ItemKind::FieldMasonedBannerPattern
            | ItemKind::BordureIndentedBannerPattern
            | ItemKind::Composter
            | ItemKind::Barrel
            | ItemKind::Smoker
            | ItemKind::BlastFurnace
            | ItemKind::CartographyTable
            | ItemKind::FletchingTable
            | ItemKind::Grindstone
            | ItemKind::SmithingTable
            | ItemKind::Stonecutter
            | ItemKind::Bell
            | ItemKind::Lantern
            | ItemKind::SoulLantern
            | ItemKind::CopperLantern
            | ItemKind::ExposedCopperLantern
            | ItemKind::WeatheredCopperLantern
            | ItemKind::OxidizedCopperLantern
            | ItemKind::WaxedCopperLantern
            | ItemKind::WaxedExposedCopperLantern
            | ItemKind::WaxedWeatheredCopperLantern
            | ItemKind::WaxedOxidizedCopperLantern
            | ItemKind::Campfire
            | ItemKind::SoulCampfire
            | ItemKind::Shroomlight
            | ItemKind::Honeycomb
            | ItemKind::BeeNest
            | ItemKind::Beehive
            | ItemKind::HoneycombBlock
            | ItemKind::Lodestone
            | ItemKind::RespawnAnchor
            | ItemKind::Candle
            | ItemKind::WhiteCandle
            | ItemKind::OrangeCandle
            | ItemKind::MagentaCandle
            | ItemKind::LightBlueCandle
            | ItemKind::YellowCandle
            | ItemKind::LimeCandle
            | ItemKind::PinkCandle
            | ItemKind::GrayCandle
            | ItemKind::LightGrayCandle
            | ItemKind::CyanCandle
            | ItemKind::PurpleCandle
            | ItemKind::BlueCandle
            | ItemKind::BrownCandle
            | ItemKind::GreenCandle
            | ItemKind::RedCandle
            | ItemKind::BlackCandle
            | ItemKind::SmallAmethystBud
            | ItemKind::MediumAmethystBud
            | ItemKind::LargeAmethystBud
            | ItemKind::AmethystCluster
            | ItemKind::OchreFroglight
            | ItemKind::VerdantFroglight
            | ItemKind::PearlescentFroglight
            | ItemKind::EchoShard
            | ItemKind::NetheriteUpgradeSmithingTemplate
            | ItemKind::SentryArmorTrimSmithingTemplate
            | ItemKind::DuneArmorTrimSmithingTemplate
            | ItemKind::CoastArmorTrimSmithingTemplate
            | ItemKind::WildArmorTrimSmithingTemplate
            | ItemKind::WardArmorTrimSmithingTemplate
            | ItemKind::EyeArmorTrimSmithingTemplate
            | ItemKind::VexArmorTrimSmithingTemplate
            | ItemKind::TideArmorTrimSmithingTemplate
            | ItemKind::SnoutArmorTrimSmithingTemplate
            | ItemKind::RibArmorTrimSmithingTemplate
            | ItemKind::SpireArmorTrimSmithingTemplate
            | ItemKind::WayfinderArmorTrimSmithingTemplate
            | ItemKind::ShaperArmorTrimSmithingTemplate
            | ItemKind::SilenceArmorTrimSmithingTemplate
            | ItemKind::RaiserArmorTrimSmithingTemplate
            | ItemKind::HostArmorTrimSmithingTemplate
            | ItemKind::FlowArmorTrimSmithingTemplate
            | ItemKind::BoltArmorTrimSmithingTemplate
            | ItemKind::AnglerPotterySherd
            | ItemKind::ArcherPotterySherd
            | ItemKind::ArmsUpPotterySherd
            | ItemKind::BladePotterySherd
            | ItemKind::BrewerPotterySherd
            | ItemKind::BurnPotterySherd
            | ItemKind::DangerPotterySherd
            | ItemKind::ExplorerPotterySherd
            | ItemKind::FlowPotterySherd
            | ItemKind::FriendPotterySherd
            | ItemKind::GusterPotterySherd
            | ItemKind::HeartPotterySherd
            | ItemKind::HeartbreakPotterySherd
            | ItemKind::HowlPotterySherd
            | ItemKind::MinerPotterySherd
            | ItemKind::MournerPotterySherd
            | ItemKind::PlentyPotterySherd
            | ItemKind::PrizePotterySherd
            | ItemKind::ScrapePotterySherd
            | ItemKind::SheafPotterySherd
            | ItemKind::ShelterPotterySherd
            | ItemKind::SkullPotterySherd
            | ItemKind::SnortPotterySherd
            | ItemKind::CopperGrate
            | ItemKind::ExposedCopperGrate
            | ItemKind::WeatheredCopperGrate
            | ItemKind::OxidizedCopperGrate
            | ItemKind::WaxedCopperGrate
            | ItemKind::WaxedExposedCopperGrate
            | ItemKind::WaxedWeatheredCopperGrate
            | ItemKind::WaxedOxidizedCopperGrate
            | ItemKind::CopperBulb
            | ItemKind::ExposedCopperBulb
            | ItemKind::WeatheredCopperBulb
            | ItemKind::OxidizedCopperBulb
            | ItemKind::WaxedCopperBulb
            | ItemKind::WaxedExposedCopperBulb
            | ItemKind::WaxedWeatheredCopperBulb
            | ItemKind::WaxedOxidizedCopperBulb
            | ItemKind::CopperChest
            | ItemKind::ExposedCopperChest
            | ItemKind::WeatheredCopperChest
            | ItemKind::OxidizedCopperChest
            | ItemKind::WaxedCopperChest
            | ItemKind::WaxedExposedCopperChest
            | ItemKind::WaxedWeatheredCopperChest
            | ItemKind::WaxedOxidizedCopperChest
            | ItemKind::CopperGolemStatue
            | ItemKind::ExposedCopperGolemStatue
            | ItemKind::WeatheredCopperGolemStatue
            | ItemKind::OxidizedCopperGolemStatue
            | ItemKind::WaxedCopperGolemStatue
            | ItemKind::WaxedExposedCopperGolemStatue
            | ItemKind::WaxedWeatheredCopperGolemStatue
            | ItemKind::WaxedOxidizedCopperGolemStatue => ItemCategory::Materials,

            ItemKind::Pumpkin
            | ItemKind::Melon
            | ItemKind::Apple
            | ItemKind::MushroomStew
            | ItemKind::Wheat
            | ItemKind::Bread
            | ItemKind::Porkchop
            | ItemKind::CookedPorkchop
            | ItemKind::MilkBucket
            | ItemKind::GoldenApple
            | ItemKind::EnchantedGoldenApple
            | ItemKind::Cod
            | ItemKind::Salmon
            | ItemKind::TropicalFish
            | ItemKind::Pufferfish
            | ItemKind::CookedCod
            | ItemKind::CookedSalmon
            | ItemKind::Cake
            | ItemKind::Cookie
            | ItemKind::MelonSlice
            | ItemKind::DriedKelp
            | ItemKind::Beef
            | ItemKind::CookedBeef
            | ItemKind::Chicken
            | ItemKind::CookedChicken
            | ItemKind::RottenFlesh
            | ItemKind::Carrot
            | ItemKind::Potato
            | ItemKind::BakedPotato
            | ItemKind::PoisonousPotato
            | ItemKind::GoldenCarrot
            | ItemKind::PumpkinPie
            | ItemKind::Rabbit
            | ItemKind::CookedRabbit
            | ItemKind::RabbitStew
            | ItemKind::Mutton
            | ItemKind::CookedMutton
            | ItemKind::ChorusFruit
            | ItemKind::Beetroot
            | ItemKind::BeetrootSoup
            | ItemKind::SuspiciousStew
            | ItemKind::SweetBerries
            | ItemKind::GlowBerries
            | ItemKind::HoneyBottle => ItemCategory::Food,

            ItemKind::String
            | ItemKind::Feather
            | ItemKind::Gunpowder
            | ItemKind::Egg
            | ItemKind::BlueEgg
            | ItemKind::BrownEgg => ItemCategory::MobDrops,

            ItemKind::ChickenSpawnEgg
            | ItemKind::CowSpawnEgg
            | ItemKind::PigSpawnEgg
            | ItemKind::SheepSpawnEgg
            | ItemKind::CamelSpawnEgg
            | ItemKind::DonkeySpawnEgg
            | ItemKind::HorseSpawnEgg
            | ItemKind::MuleSpawnEgg
            | ItemKind::CatSpawnEgg
            | ItemKind::ParrotSpawnEgg
            | ItemKind::WolfSpawnEgg
            | ItemKind::ArmadilloSpawnEgg
            | ItemKind::BatSpawnEgg
            | ItemKind::BeeSpawnEgg
            | ItemKind::FoxSpawnEgg
            | ItemKind::GoatSpawnEgg
            | ItemKind::LlamaSpawnEgg
            | ItemKind::OcelotSpawnEgg
            | ItemKind::PandaSpawnEgg
            | ItemKind::PolarBearSpawnEgg
            | ItemKind::RabbitSpawnEgg
            | ItemKind::AxolotlSpawnEgg
            | ItemKind::CodSpawnEgg
            | ItemKind::DolphinSpawnEgg
            | ItemKind::FrogSpawnEgg
            | ItemKind::GlowSquidSpawnEgg
            | ItemKind::NautilusSpawnEgg
            | ItemKind::PufferfishSpawnEgg
            | ItemKind::SalmonSpawnEgg
            | ItemKind::SquidSpawnEgg
            | ItemKind::TadpoleSpawnEgg
            | ItemKind::TropicalFishSpawnEgg
            | ItemKind::TurtleSpawnEgg
            | ItemKind::AllaySpawnEgg
            | ItemKind::MooshroomSpawnEgg
            | ItemKind::SnifferSpawnEgg
            | ItemKind::SulfurCubeSpawnEgg
            | ItemKind::CopperGolemSpawnEgg
            | ItemKind::IronGolemSpawnEgg
            | ItemKind::SnowGolemSpawnEgg
            | ItemKind::TraderLlamaSpawnEgg
            | ItemKind::VillagerSpawnEgg
            | ItemKind::WanderingTraderSpawnEgg
            | ItemKind::BoggedSpawnEgg
            | ItemKind::CamelHuskSpawnEgg
            | ItemKind::DrownedSpawnEgg
            | ItemKind::HuskSpawnEgg
            | ItemKind::ParchedSpawnEgg
            | ItemKind::SkeletonSpawnEgg
            | ItemKind::SkeletonHorseSpawnEgg
            | ItemKind::StraySpawnEgg
            | ItemKind::WitherSpawnEgg
            | ItemKind::WitherSkeletonSpawnEgg
            | ItemKind::ZombieSpawnEgg
            | ItemKind::ZombieHorseSpawnEgg
            | ItemKind::ZombieNautilusSpawnEgg
            | ItemKind::ZombieVillagerSpawnEgg
            | ItemKind::CaveSpiderSpawnEgg
            | ItemKind::SpiderSpawnEgg
            | ItemKind::BreezeSpawnEgg
            | ItemKind::CreakingSpawnEgg
            | ItemKind::CreeperSpawnEgg
            | ItemKind::ElderGuardianSpawnEgg
            | ItemKind::GuardianSpawnEgg
            | ItemKind::PhantomSpawnEgg
            | ItemKind::SilverfishSpawnEgg
            | ItemKind::SlimeSpawnEgg
            | ItemKind::WardenSpawnEgg
            | ItemKind::WitchSpawnEgg
            | ItemKind::EvokerSpawnEgg
            | ItemKind::PillagerSpawnEgg
            | ItemKind::RavagerSpawnEgg
            | ItemKind::VindicatorSpawnEgg
            | ItemKind::VexSpawnEgg
            | ItemKind::BlazeSpawnEgg
            | ItemKind::GhastSpawnEgg
            | ItemKind::HappyGhastSpawnEgg
            | ItemKind::HoglinSpawnEgg
            | ItemKind::MagmaCubeSpawnEgg
            | ItemKind::PiglinSpawnEgg
            | ItemKind::PiglinBruteSpawnEgg
            | ItemKind::StriderSpawnEgg
            | ItemKind::ZoglinSpawnEgg
            | ItemKind::ZombifiedPiglinSpawnEgg
            | ItemKind::EnderDragonSpawnEgg
            | ItemKind::EndermanSpawnEgg
            | ItemKind::EndermiteSpawnEgg
            | ItemKind::ShulkerSpawnEgg => ItemCategory::MobDrops,

            ItemKind::Air
            | ItemKind::HeavyCore
            | ItemKind::Spawner
            | ItemKind::CreakingHeart
            | ItemKind::EndPortalFrame
            | ItemKind::DragonEgg
            | ItemKind::CommandBlock
            | ItemKind::Barrier
            | ItemKind::Light
            | ItemKind::RepeatingCommandBlock
            | ItemKind::ChainCommandBlock
            | ItemKind::StructureVoid
            | ItemKind::TurtleEgg
            | ItemKind::SnifferEgg
            | ItemKind::DriedGhast
            | ItemKind::StructureBlock
            | ItemKind::Jigsaw
            | ItemKind::TestBlock
            | ItemKind::TestInstanceBlock
            | ItemKind::Painting
            | ItemKind::WrittenBook
            | ItemKind::ItemFrame
            | ItemKind::GlowItemFrame
            | ItemKind::FlowerPot
            | ItemKind::SkeletonSkull
            | ItemKind::WitherSkeletonSkull
            | ItemKind::PlayerHead
            | ItemKind::ZombieHead
            | ItemKind::CreeperHead
            | ItemKind::DragonHead
            | ItemKind::PiglinHead
            | ItemKind::ArmorStand
            | ItemKind::CommandBlockMinecart
            | ItemKind::EndCrystal
            | ItemKind::KnowledgeBook
            | ItemKind::DebugStick
            | ItemKind::MusicDisc13
            | ItemKind::MusicDiscCat
            | ItemKind::MusicDiscBlocks
            | ItemKind::MusicDiscBounce
            | ItemKind::MusicDiscChirp
            | ItemKind::MusicDiscCreator
            | ItemKind::MusicDiscCreatorMusicBox
            | ItemKind::MusicDiscFar
            | ItemKind::MusicDiscLavaChicken
            | ItemKind::MusicDiscMall
            | ItemKind::MusicDiscMellohi
            | ItemKind::MusicDiscStal
            | ItemKind::MusicDiscStrad
            | ItemKind::MusicDiscWard
            | ItemKind::MusicDisc11
            | ItemKind::MusicDiscWait
            | ItemKind::MusicDiscOtherside
            | ItemKind::MusicDiscRelic
            | ItemKind::MusicDisc5
            | ItemKind::MusicDiscPigstep
            | ItemKind::MusicDiscPrecipice
            | ItemKind::MusicDiscTears
            | ItemKind::DiscFragment5
            | ItemKind::Frogspawn
            | ItemKind::TrialSpawner
            | ItemKind::TrialKey
            | ItemKind::OminousTrialKey
            | ItemKind::Vault
            | ItemKind::OminousBottle => ItemCategory::Other,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn category(kind: ItemKind) -> ItemCategory {
        DefaultItemCategoryProfile.map_item_kind(&kind)
    }

    #[test]
    fn maps_representative_items_to_each_category() {
        assert!(matches!(category(ItemKind::Stone), ItemCategory::Rocks));
        assert!(matches!(category(ItemKind::OakPlanks), ItemCategory::Wood));
        assert!(matches!(
            category(ItemKind::GrassBlock),
            ItemCategory::Nature
        ));
        assert!(matches!(
            category(ItemKind::DiamondPickaxe),
            ItemCategory::Tools
        ));
        assert!(matches!(
            category(ItemKind::IronIngot),
            ItemCategory::Materials
        ));
        assert!(matches!(category(ItemKind::Bread), ItemCategory::Food));
        assert!(matches!(category(ItemKind::String), ItemCategory::MobDrops));
        assert!(matches!(
            category(ItemKind::MusicDiscCat),
            ItemCategory::Other
        ));
    }

    #[test]
    fn follows_category_precedence_for_overlapping_item_roles() {
        assert!(matches!(category(ItemKind::Stick), ItemCategory::Wood));
        assert!(matches!(
            category(ItemKind::EnchantedBook),
            ItemCategory::Tools
        ));
        assert!(matches!(
            category(ItemKind::RottenFlesh),
            ItemCategory::Food
        ));
        assert!(matches!(category(ItemKind::MilkBucket), ItemCategory::Food));
        assert!(matches!(
            category(ItemKind::ChickenSpawnEgg),
            ItemCategory::MobDrops
        ));
        assert!(matches!(
            category(ItemKind::BreezeRod),
            ItemCategory::Materials
        ));
        assert!(matches!(category(ItemKind::Air), ItemCategory::Other));
        assert!(matches!(category(ItemKind::Dirt), ItemCategory::Nature));
        assert!(matches!(category(ItemKind::Sand), ItemCategory::Nature));
        assert!(matches!(category(ItemKind::Poppy), ItemCategory::Nature));
        assert!(matches!(
            category(ItemKind::BrownMushroom),
            ItemCategory::Nature
        ));
    }
}
