/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a planner request */
        post: operations["api_queue_queue_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get planner queue and work-unit pool status */
        get: operations["api_status_get_system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available crafting recipes */
        get: operations["api_crafting_list_recipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crafting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List craft job statuses */
        get: operations["api_crafting_list_craft_statuses"];
        put?: never;
        /** Queue a resolved craft plan */
        post: operations["api_crafting_queue_craft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crafting/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a crafting plan */
        post: operations["api_crafting_resolve_crafting_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crafting/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a craft job status */
        get: operations["api_crafting_get_craft_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search indexed storage contents */
        get: operations["api_storage_list_storage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/{item_kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all indexed stacks for an item kind */
        get: operations["api_storage_get_item_kind_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all containers with their current contents */
        get: operations["api_containers_list_containers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/containers/grouped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all containers grouped by region */
        get: operations["api_containers_list_containers_grouped"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/containers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a container with its current contents */
        get: operations["api_containers_get_container"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all container regions */
        get: operations["api_regions_list_regions"];
        put?: never;
        /** Create a container region */
        post: operations["api_regions_create_region"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a container region */
        get: operations["api_regions_get_region"];
        /** Replace a container region */
        put: operations["api_regions_update_region"];
        post?: never;
        /** Delete a container region */
        delete: operations["api_regions_delete_region"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContainerPosition: {
            x: number;
            y: number;
            z: number;
        };
        ContainerRegionGroup: {
            region_id: string;
            region_type?: components["schemas"]["RegionType"];
            priority?: number | null;
            containers: components["schemas"]["ContainerView"][];
        };
        ContainerView: {
            id: string;
            region_id: string;
            position: components["schemas"]["ContainerPosition"];
            capacity: number;
            contents: components["schemas"]["ItemStackView"][];
        };
        CraftExecutionNode: {
            key: string;
            item_kind: string;
            required_quantity: number;
            completed_quantity: number;
            state: string;
            assigned_region_id?: string | null;
            error?: string | null;
            operation?: components["schemas"]["CraftExecutionOperation"];
            children: components["schemas"]["CraftExecutionNode"][];
            kind: components["schemas"]["CraftExecutionNodeKind"];
        };
        CraftExecutionNodeKind: {
            recipe_id: string;
            engine_type: string;
            planned_crafts: number;
            completed_crafts: number;
            output_yield: number;
            /** @enum {string} */
            type: "recipe";
        } | {
            /** @enum {string} */
            type: "storage" | "any";
        };
        CraftExecutionOperation: {
            kind: string;
            state: string;
            completed_amount: number;
            error?: string | null;
        };
        CraftJobDetail: {
            job: components["schemas"]["CraftJobStatus"];
            root: components["schemas"]["CraftExecutionNode"];
        };
        /** @enum {string} */
        CraftJobState: "queued" | "waiting" | "running" | "completed" | "failed";
        CraftJobStatus: {
            id: string;
            target_item_kind: string;
            target_quantity: number;
            selections: {
                [key: string]: components["schemas"]["CraftSelection"];
            };
            state: components["schemas"]["CraftJobState"];
            completed_quantity: number;
            error?: string | null;
        };
        CraftNode: {
            key: string;
            item_kind: string;
            quantity: number;
            children: components["schemas"]["CraftNode"][];
            kind: components["schemas"]["CraftNodeKind"];
        };
        CraftNodeKind: {
            recipe_id: string;
            crafts: number;
            output_yield: number;
            selected: boolean;
            /** @enum {string} */
            type: "recipe";
        } | {
            available: number;
            selected: boolean;
            /** @enum {string} */
            type: "storage";
        } | {
            options: components["schemas"]["CraftOption"][];
            /** @enum {string} */
            type: "choice";
        } | {
            /** @enum {string} */
            type: "any" | "deferred";
        };
        CraftOption: {
            recipe_id: string;
            preview: Record<string, never>;
            available: boolean;
            /** @enum {string} */
            type: "recipe";
        } | {
            preview: Record<string, never>;
            available: boolean;
            /** @enum {string} */
            type: "storage";
        } | {
            preview: Record<string, never>;
            /** @enum {string} */
            type: "any";
        };
        CraftPlan: {
            target_item_kind: string;
            target_quantity: number;
            root: components["schemas"]["CraftNode"];
            raw_materials: components["schemas"]["RawMaterialRequirement"][];
            unresolved: boolean;
        };
        CraftPlanRequest: {
            item_kind: string;
            amount: number;
            selections: {
                [key: string]: components["schemas"]["CraftSelection"];
            };
            job_id?: string | null;
        };
        CraftQueueResponse: {
            job_id: string;
        };
        CraftSelection: {
            recipe_id: string;
            /** @enum {string} */
            type: "recipe";
        } | {
            /** @enum {string} */
            type: "storage" | "any";
        };
        IngredientResponse: {
            item_kind: string;
            quantity: number;
        };
        ItemKindDetails: {
            item_kind: string;
            total_quantity: number;
            stack_count: number;
            container_count: number;
            stacks: components["schemas"]["ItemKindStack"][];
        };
        ItemKindStack: {
            stack_id: string;
            container_id: string;
            region_id: string;
            region_type: string;
            position: components["schemas"]["ItemPosition"];
            slot: number;
            quantity: number;
            components: Record<string, never>;
            components_digest: string;
        };
        ItemPosition: {
            x: number;
            y: number;
            z: number;
        };
        ItemStackView: {
            id: string;
            container_id: string;
            item_kind: string;
            slot: number;
            components: Record<string, never>;
            quantity: number;
            components_digest: string;
        };
        PlannerQueueItem: {
            position: number;
            kind: components["schemas"]["PlannerRequestKind"];
            detail?: string | null;
        };
        /** @enum {string} */
        PlannerRequest: "IndexRegions" | "CycleCount" | "Putaway";
        /** @enum {string} */
        PlannerRequestKind: "index_regions" | "cycle_count" | "putaway";
        QueueResponse: {
            job_id?: string | null;
        };
        RawMaterialRequirement: {
            item_kind: string;
            quantity: number;
            available: number;
        };
        RecipeResponse: {
            id: string;
            output_item_kind: string;
            output_yield: number;
            engine_type: string;
            ingredients: components["schemas"]["IngredientResponse"][];
        };
        Region: {
            id: string;
            type: components["schemas"]["RegionType"];
            priority: number;
            world_region: components["schemas"]["RegionWorld"];
        };
        RegionPoint: {
            x: number;
            y: number;
            z: number;
        };
        RegionRequest: {
            type: components["schemas"]["RegionType"];
            priority: number;
            world_region: components["schemas"]["RegionWorld"];
        };
        /** @enum {string} */
        RegionType: "bulk" | "pickface" | "putaway" | "processing" | "order";
        RegionWorld: {
            pos1: components["schemas"]["RegionPoint"];
            pos2: components["schemas"]["RegionPoint"];
        };
        StorageItem: {
            item_kind: string;
            quantity: number;
            stack_count: number;
            container_count: number;
        };
        StorageQuery: {
            q?: string | null;
            region_id?: string | null;
            min_quantity?: number | null;
            sort_by?: components["schemas"]["StorageSortBy"];
            sort_direction?: components["schemas"]["StorageSortDirection"];
        };
        /** @enum {string} */
        StorageSortBy: "name" | "quantity" | "stacks" | "containers";
        /** @enum {string} */
        StorageSortDirection: "asc" | "desc";
        SystemStatusResponse: {
            planner_queue: components["schemas"]["PlannerQueueItem"][];
            work_unit_pool: components["schemas"]["WorkUnitPoolSummary"];
            work_units: components["schemas"]["WorkUnitStatus"][];
        };
        /** @enum {string} */
        WorkUnitKind: "index_region" | "index_container" | "transfer" | "craft";
        WorkUnitPoolSummary: {
            total: number;
            queued: number;
            claimed: number;
            completed: number;
        };
        WorkUnitStatus: {
            id: string;
            kind: components["schemas"]["WorkUnitKind"];
            state: components["schemas"]["WorkUnitStatusState"];
            priority: number;
            completed_steps?: number | null;
            total_steps?: number | null;
            detail: string;
        };
        /** @enum {string} */
        WorkUnitStatusState: "queued" | "claimed" | "completed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_queue_queue_request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
        };
    };
    api_status_get_system_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    api_crafting_list_recipes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"][];
                };
            };
        };
    };
    api_crafting_list_craft_statuses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraftJobStatus"][];
                };
            };
        };
    };
    api_crafting_queue_craft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CraftPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraftQueueResponse"];
                };
            };
        };
    };
    api_crafting_resolve_crafting_plan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CraftPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraftPlan"];
                };
            };
        };
    };
    api_crafting_get_craft_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraftJobDetail"];
                };
            };
        };
    };
    api_storage_list_storage: {
        parameters: {
            query?: {
                q?: string | null;
                region_id?: string | null;
                min_quantity?: number | null;
                sort_by?: components["schemas"]["StorageSortBy"];
                sort_direction?: components["schemas"]["StorageSortDirection"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageItem"][];
                };
            };
        };
    };
    api_storage_get_item_kind_details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemKindDetails"];
                };
            };
        };
    };
    api_containers_list_containers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerView"][];
                };
            };
        };
    };
    api_containers_list_containers_grouped: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerRegionGroup"][];
                };
            };
        };
    };
    api_containers_get_container: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerView"];
                };
            };
        };
    };
    api_regions_list_regions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"][];
                };
            };
        };
    };
    api_regions_create_region: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"];
                };
            };
        };
    };
    api_regions_get_region: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"];
                };
            };
        };
    };
    api_regions_update_region: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"];
                };
            };
        };
    };
    api_regions_delete_region: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
}
