/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a planner request */
        post: operations["api_queue_queue_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search indexed storage contents */
        get: operations["api_storage_list_storage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/{item_kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all indexed stacks for an item kind */
        get: operations["api_storage_get_item_kind_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all containers with their current contents */
        get: operations["api_containers_list_containers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/containers/grouped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all containers grouped by region */
        get: operations["api_containers_list_containers_grouped"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/containers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a container with its current contents */
        get: operations["api_containers_get_container"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all container regions */
        get: operations["api_regions_list_regions"];
        put?: never;
        /** Create a container region */
        post: operations["api_regions_create_region"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a container region */
        get: operations["api_regions_get_region"];
        /** Replace a container region */
        put: operations["api_regions_update_region"];
        post?: never;
        /** Delete a container region */
        delete: operations["api_regions_delete_region"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContainerPosition: {
            x: number;
            y: number;
            z: number;
        };
        ContainerRegionGroup: {
            region_id: string;
            region_type?: components["schemas"]["RegionType"];
            priority?: number | null;
            containers: components["schemas"]["ContainerView"][];
        };
        ContainerView: {
            id: string;
            region_id: string;
            position: components["schemas"]["ContainerPosition"];
            capacity: number;
            contents: components["schemas"]["ItemStackView"][];
        };
        ItemKindDetails: {
            item_kind: string;
            total_quantity: number;
            stack_count: number;
            container_count: number;
            stacks: components["schemas"]["ItemKindStack"][];
        };
        ItemKindStack: {
            stack_id: string;
            container_id: string;
            region_id: string;
            region_type: string;
            position: components["schemas"]["ItemPosition"];
            slot: number;
            quantity: number;
            components: Record<string, never>;
            components_digest: string;
        };
        ItemPosition: {
            x: number;
            y: number;
            z: number;
        };
        ItemStackView: {
            id: string;
            container_id: string;
            item_kind: string;
            slot: number;
            components: Record<string, never>;
            quantity: number;
            components_digest: string;
        };
        /** @enum {string} */
        PlannerRequest: "IndexRegions" | "CycleCount" | "Putaway";
        Region: {
            id: string;
            type: components["schemas"]["RegionType"];
            priority: number;
            world_region: components["schemas"]["RegionWorld"];
        };
        RegionPoint: {
            x: number;
            y: number;
            z: number;
        };
        RegionRequest: {
            type: components["schemas"]["RegionType"];
            priority: number;
            world_region: components["schemas"]["RegionWorld"];
        };
        /** @enum {string} */
        RegionType: "bulk" | "pickface" | "putaway" | "processing" | "order";
        RegionWorld: {
            pos1: components["schemas"]["RegionPoint"];
            pos2: components["schemas"]["RegionPoint"];
        };
        StorageItem: {
            item_kind: string;
            quantity: number;
            stack_count: number;
            container_count: number;
        };
        StorageQuery: {
            q?: string | null;
            region_id?: string | null;
            min_quantity?: number | null;
            sort_by?: components["schemas"]["StorageSortBy"];
            sort_direction?: components["schemas"]["StorageSortDirection"];
        };
        /** @enum {string} */
        StorageSortBy: "name" | "quantity" | "stacks" | "containers";
        /** @enum {string} */
        StorageSortDirection: "asc" | "desc";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_queue_queue_request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannerRequest"];
            };
        };
        responses: never;
    };
    api_storage_list_storage: {
        parameters: {
            query?: {
                q?: string | null;
                region_id?: string | null;
                min_quantity?: number | null;
                sort_by?: components["schemas"]["StorageSortBy"];
                sort_direction?: components["schemas"]["StorageSortDirection"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageItem"][];
                };
            };
        };
    };
    api_storage_get_item_kind_details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemKindDetails"];
                };
            };
        };
    };
    api_containers_list_containers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerView"][];
                };
            };
        };
    };
    api_containers_list_containers_grouped: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerRegionGroup"][];
                };
            };
        };
    };
    api_containers_get_container: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerView"];
                };
            };
        };
    };
    api_regions_list_regions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"][];
                };
            };
        };
    };
    api_regions_create_region: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"];
                };
            };
        };
    };
    api_regions_get_region: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"];
                };
            };
        };
    };
    api_regions_update_region: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"];
                };
            };
        };
    };
    api_regions_delete_region: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
}
