[package]
edition = "2024"
name = "worker"
version = "0.1.0"

[dependencies]
anyhow = "1.0.104"
azalea = { git = "https://github.com/azalea-rs/azalea.git", default-features = false, features = [
    "serde",
    "online-mode",
] }
azalea-crypto = { git = "https://github.com/azalea-rs/azalea.git" }
common = { path = "../common" }
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml2 = "0.1.3"
tokio = { version = "1.53.1", features = ["macros"] }
