use enum_dispatch::enum_dispatch;
use serde::{Deserialize, Serialize};

use crate::{
    ids::WorkUnitId,
    work_units::{
        index_container::IndexContainerWorkUnit, index_region::IndexRegionWorkUnit,
        transfer::TransferWorkUnit,
    },
};

/// Work units are generated by the server, and clients picked them up from a pool by locking them.
///
/// Work units are self-contained, their outputs are Option<> within them, so a completed/partially completed
/// work unit is passed as-is back to the server
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct WorkUnit {
    /// ID of this Work Unit
    pub id: WorkUnitId,
    /// Information about what is required for this work unit
    pub data: WorkUnitData,
}

#[enum_dispatch(WorkUnitDone)]
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum WorkUnitData {
    IndexRegion(IndexRegionWorkUnit),
    IndexContainer(IndexContainerWorkUnit),
    Transfer(TransferWorkUnit),
}

#[enum_dispatch]
pub trait WorkUnitDone {
    fn is_done(&self) -> bool;
}

impl WorkUnitDone for WorkUnit {
    fn is_done(&self) -> bool {
        self.data.is_done()
    }
}

impl<T> From<T> for WorkUnit
where
    T: Into<WorkUnitData>,
{
    fn from(value: T) -> Self {
        Self {
            id: WorkUnitId::new(),
            data: value.into(),
        }
    }
}
