use uuid::Uuid;

use crate::{item_stack::ItemStack, vec::Point};

/// Work units are generated by the server, and clients picked them up from a pool by locking them.
/// 
/// Work units are self-contained, their outputs are Option<> within them, so a completed/partially completed
/// work unit is passed as-is back to the server
pub struct WorkUnit {
    pub id: Uuid,
    pub data: WorkUnitData,
}

pub enum WorkUnitData {
    IndexContainer(IndexContainerWorkUnit),
}

/// Indexes a container at a point
pub struct IndexContainerWorkUnit {
    pub position: Point,

    pub output: Option<Vec<ItemStack>>,
}

